package com.hand.hap.hapExam.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.core.annotation.Children;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;

import com.hand.hap.system.dto.BaseDTO;

import java.util.Date;
import java.util.List;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.format.annotation.DateTimeFormat;

@ExtensionAttribute(disable = true)
@Table(name = "hap_om_order_headers")
public class OmOrderHeaders extends BaseDTO {

    public static final String FIELD_HEADER_ID = "headerId";
    public static final String FIELD_ORDER_NUMBER = "orderNumber";
    public static final String FIELD_COMPANY_ID = "companyId";
    public static final String FIELD_ORDER_DATE = "orderDate";
    public static final String FIELD_ORDER_STATUS = "orderStatus";
    public static final String FIELD_CUSTOMER_ID = "customerId";


    @Id
    @GeneratedValue
    private Long headerId; //订单头ID

    @NotEmpty
    @Length(max = 60)
    private String orderNumber; //订单编号

    @NotNull
    private Long companyId; //公司ID

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date orderDate; //订单日期

    @NotEmpty
    @Length(max = 30)
    private String orderStatus; //订单状态

    @NotNull
    private Long customerId; //客户ID

    //物料ID的冗余字段
    @Transient
    private Long inventoryItemId; //物料ID

    @Transient
    private String customerName;

    @Transient
    private String companyName;

    @Transient
    private Long orderAmount;

    @Children
    @Transient
    private List<OmOrderLines> orderLines;

    public void setHeaderId(Long headerId) {
        this.headerId = headerId;
    }

    public Long getHeaderId() {
        return headerId;
    }

    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    public String getOrderNumber() {
        return orderNumber;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    public Date getOrderDate() {
        return orderDate;
    }

    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    public String getOrderStatus() {
        return orderStatus;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    public Long getCustomerId() {
        return customerId;
    }

    public Long getInventoryItemId() {
        return inventoryItemId;
    }

    public void setInventoryItemId(Long inventoryItemId) {
        this.inventoryItemId = inventoryItemId;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public Long getOrderAmount() {
        return orderAmount;
    }

    public void setOrderAmount(Long orderAmount) {
        this.orderAmount = orderAmount;
    }

    public List<OmOrderLines> getOrderLines() {
        return orderLines;
    }

    public void setOrderLines(List<OmOrderLines> orderLines) {
        this.orderLines = orderLines;
    }
}
